//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub b7c720da-46d4-4dad-8884-7c110353c0c4 aws-my-sample-app-android-v0.15";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:a969decf-5761-4328-b6fe-42ebc2402fb7";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "cf9756801ba947c1909786f511d11f1c";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "656188433799";
    // SNS PLATFORM APPLICATION ARN
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN =
        "arn:aws:sns:us-east-1:126611141558:app/GCM/myselffitbeta_MOBILEHUB_184640436";
    public static final Regions AMAZON_SNS_REGION =
         Regions.fromName("us-east-1");
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN =
        "arn:aws:sns:us-east-1:126611141558:myselffitbeta_alldevices_MOBILEHUB_184640436";
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_RESULT_TOPIC_ARN =
        "arn:aws:sns:us-east-1:126611141558:UserResult";
    // SNS PLATFORM TOPIC ARNS
    public static final String[] AMAZON_SNS_TOPIC_ARNS =
        {"arn:aws:sns:us-east-1:126611141558:myselffitbeta_trainers_MOBILEHUB_184640436","arn:aws:sns:us-east-1:126611141558:myselffitbeta_thirdtopic_MOBILEHUB_184640436"};
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "myselffitbeta-userfiles-mobilehub-184640436";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_SUQe1bVPe";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "k75nv4hud9hrs5doc8p2459n7";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "2pitj45tuolsedn0et8sl8sc4o0d4is74bv4qatcjg3sos68o6q";
}
